version: "3.8"

services:

  userpokemon-service:
    container_name: userpokemon-service
    build:
      context: ./
    depends_on:
      - userpokemon-mongodb
    ports:
      - "8082:8082"
    networks:
      - spring-net
    restart: "no"

  userpokemon-mongodb:
    container_name: userpokemon-mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Teun
      MONGO_INITDB_DATABASE: userpokemon
    networks:
      - spring-net
    volumes:
      - userpokemon:/data/db

networks:
  spring-net:
    name: spring-net
    driver: bridge

volumes:
  userpokemon: