apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: userpokemon-mongodb
  name: userpokemon-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: userpokemon-mongodb
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/spring-net: "true"
        io.kompose.service: userpokemon-mongodb
    spec:
      containers:
        - env:
            - name: MONGO_INITDB_DATABASE
              value: userpokemon
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: Teun
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
          image: mongo:latest
          name: userpokemon-mongodb
          ports:
            - containerPort: 27017
          resources: {}
          volumeMounts:
            - mountPath: /data/db
              name: userpokemon
      restartPolicy: Always
      volumes:
        - name: userpokemon
          persistentVolumeClaim:
            claimName: userpokemon
status: {}
