apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.network/spring-net: "true"
    io.kompose.service: userpokemon-service
  name: userpokemon-service
spec:
  containers:
    - image: userpokemon-service
      name: userpokemon-service
      ports:
        - containerPort: 8082
      resources: {}
  restartPolicy: OnFailure
status: {}
